CREATE TABLE scan
(
	id SERIAL NOT NULL PRIMARY KEY,
	"userId" uuid NOT NULL,
	code CHARACTER VARYING(255) NOT NULL,
	"deletedAt" CHARACTER VARYING(255),
	"createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE scan OWNER TO "dbUser";
